name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Deno
        uses: denoland/setup-deno@v1.1.2
        with:
          deno-version: v1.x
      - name: Set up Node
        uses: actions/setup-node@v3.7.0
        with:
          node-version: "18"
      - name: Set up Terser
        run: npm install terser@5.19.2 -g
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Build
        run: |
          mkdir -p dist
          deno bundle src/main.ts dist/hello.js
      - name: Compress
        run: |
          echo '!function(){' >> dist/temp.js
          cat dist/hello.js >> dist/temp.js
          echo '}()' >> dist/temp.js
          #terser --compress --mangle --mangle-props --output dist/hello.min.js dist/temp.js
          terser --compress --output dist/hello.min.js dist/temp.js
          rm -rf dist/temp.js
      - name: Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: "master"
          commit-message: "Build by GitHub Actions"
          name: Candison
          email: kandisheng@163.com
