name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Deno
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: v1.x
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build
        run: |
          mkdir -p dist
          deno bundle src/main.ts dist/hello.js
      - name: Push
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: "master"
          commit-message: "Build by GitHub Actions"
          name: Candison
          email: kandisheng@163.com
